/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package humanlayerapi

import (
	"encoding/json"
)

// checks if the ContactChannelOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactChannelOutput{}

// ContactChannelOutput struct for ContactChannelOutput
type ContactChannelOutput struct {
	Slack    NullableSlackContactChannelOutput `json:"slack,omitempty"`
	Sms      NullableSMSContactChannel         `json:"sms,omitempty"`
	Whatsapp NullableWhatsAppContactChannel    `json:"whatsapp,omitempty"`
	Email    NullableEmailContactChannel       `json:"email,omitempty"`
}

// NewContactChannelOutput instantiates a new ContactChannelOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactChannelOutput() *ContactChannelOutput {
	this := ContactChannelOutput{}
	return &this
}

// NewContactChannelOutputWithDefaults instantiates a new ContactChannelOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactChannelOutputWithDefaults() *ContactChannelOutput {
	this := ContactChannelOutput{}
	return &this
}

// GetSlack returns the Slack field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContactChannelOutput) GetSlack() SlackContactChannelOutput {
	if o == nil || IsNil(o.Slack.Get()) {
		var ret SlackContactChannelOutput
		return ret
	}
	return *o.Slack.Get()
}

// GetSlackOk returns a tuple with the Slack field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContactChannelOutput) GetSlackOk() (*SlackContactChannelOutput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slack.Get(), o.Slack.IsSet()
}

// HasSlack returns a boolean if a field has been set.
func (o *ContactChannelOutput) HasSlack() bool {
	if o != nil && o.Slack.IsSet() {
		return true
	}

	return false
}

// SetSlack gets a reference to the given NullableSlackContactChannelOutput and assigns it to the Slack field.
func (o *ContactChannelOutput) SetSlack(v SlackContactChannelOutput) {
	o.Slack.Set(&v)
}

// SetSlackNil sets the value for Slack to be an explicit nil
func (o *ContactChannelOutput) SetSlackNil() {
	o.Slack.Set(nil)
}

// UnsetSlack ensures that no value is present for Slack, not even an explicit nil
func (o *ContactChannelOutput) UnsetSlack() {
	o.Slack.Unset()
}

// GetSms returns the Sms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContactChannelOutput) GetSms() SMSContactChannel {
	if o == nil || IsNil(o.Sms.Get()) {
		var ret SMSContactChannel
		return ret
	}
	return *o.Sms.Get()
}

// GetSmsOk returns a tuple with the Sms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContactChannelOutput) GetSmsOk() (*SMSContactChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sms.Get(), o.Sms.IsSet()
}

// HasSms returns a boolean if a field has been set.
func (o *ContactChannelOutput) HasSms() bool {
	if o != nil && o.Sms.IsSet() {
		return true
	}

	return false
}

// SetSms gets a reference to the given NullableSMSContactChannel and assigns it to the Sms field.
func (o *ContactChannelOutput) SetSms(v SMSContactChannel) {
	o.Sms.Set(&v)
}

// SetSmsNil sets the value for Sms to be an explicit nil
func (o *ContactChannelOutput) SetSmsNil() {
	o.Sms.Set(nil)
}

// UnsetSms ensures that no value is present for Sms, not even an explicit nil
func (o *ContactChannelOutput) UnsetSms() {
	o.Sms.Unset()
}

// GetWhatsapp returns the Whatsapp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContactChannelOutput) GetWhatsapp() WhatsAppContactChannel {
	if o == nil || IsNil(o.Whatsapp.Get()) {
		var ret WhatsAppContactChannel
		return ret
	}
	return *o.Whatsapp.Get()
}

// GetWhatsappOk returns a tuple with the Whatsapp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContactChannelOutput) GetWhatsappOk() (*WhatsAppContactChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Whatsapp.Get(), o.Whatsapp.IsSet()
}

// HasWhatsapp returns a boolean if a field has been set.
func (o *ContactChannelOutput) HasWhatsapp() bool {
	if o != nil && o.Whatsapp.IsSet() {
		return true
	}

	return false
}

// SetWhatsapp gets a reference to the given NullableWhatsAppContactChannel and assigns it to the Whatsapp field.
func (o *ContactChannelOutput) SetWhatsapp(v WhatsAppContactChannel) {
	o.Whatsapp.Set(&v)
}

// SetWhatsappNil sets the value for Whatsapp to be an explicit nil
func (o *ContactChannelOutput) SetWhatsappNil() {
	o.Whatsapp.Set(nil)
}

// UnsetWhatsapp ensures that no value is present for Whatsapp, not even an explicit nil
func (o *ContactChannelOutput) UnsetWhatsapp() {
	o.Whatsapp.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContactChannelOutput) GetEmail() EmailContactChannel {
	if o == nil || IsNil(o.Email.Get()) {
		var ret EmailContactChannel
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContactChannelOutput) GetEmailOk() (*EmailContactChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *ContactChannelOutput) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableEmailContactChannel and assigns it to the Email field.
func (o *ContactChannelOutput) SetEmail(v EmailContactChannel) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *ContactChannelOutput) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *ContactChannelOutput) UnsetEmail() {
	o.Email.Unset()
}

func (o ContactChannelOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactChannelOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Slack.IsSet() {
		toSerialize["slack"] = o.Slack.Get()
	}
	if o.Sms.IsSet() {
		toSerialize["sms"] = o.Sms.Get()
	}
	if o.Whatsapp.IsSet() {
		toSerialize["whatsapp"] = o.Whatsapp.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	return toSerialize, nil
}

type NullableContactChannelOutput struct {
	value *ContactChannelOutput
	isSet bool
}

func (v NullableContactChannelOutput) Get() *ContactChannelOutput {
	return v.value
}

func (v *NullableContactChannelOutput) Set(val *ContactChannelOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableContactChannelOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableContactChannelOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactChannelOutput(val *ContactChannelOutput) *NullableContactChannelOutput {
	return &NullableContactChannelOutput{value: val, isSet: true}
}

func (v NullableContactChannelOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactChannelOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
