/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package humanlayerapi

import (
	"encoding/json"
	"time"
)

// checks if the HumanContactStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HumanContactStatus{}

// HumanContactStatus struct for HumanContactStatus
type HumanContactStatus struct {
	RequestedAt        NullableTime   `json:"requested_at,omitempty"`
	RespondedAt        NullableTime   `json:"responded_at,omitempty"`
	Response           NullableString `json:"response,omitempty"`
	ResponseOptionName NullableString `json:"response_option_name,omitempty"`
	SlackMessageTs     NullableString `json:"slack_message_ts,omitempty"`
}

// NewHumanContactStatus instantiates a new HumanContactStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHumanContactStatus() *HumanContactStatus {
	this := HumanContactStatus{}
	return &this
}

// NewHumanContactStatusWithDefaults instantiates a new HumanContactStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHumanContactStatusWithDefaults() *HumanContactStatus {
	this := HumanContactStatus{}
	return &this
}

// GetRequestedAt returns the RequestedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HumanContactStatus) GetRequestedAt() time.Time {
	if o == nil || IsNil(o.RequestedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RequestedAt.Get()
}

// GetRequestedAtOk returns a tuple with the RequestedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HumanContactStatus) GetRequestedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestedAt.Get(), o.RequestedAt.IsSet()
}

// HasRequestedAt returns a boolean if a field has been set.
func (o *HumanContactStatus) HasRequestedAt() bool {
	if o != nil && o.RequestedAt.IsSet() {
		return true
	}

	return false
}

// SetRequestedAt gets a reference to the given NullableTime and assigns it to the RequestedAt field.
func (o *HumanContactStatus) SetRequestedAt(v time.Time) {
	o.RequestedAt.Set(&v)
}

// SetRequestedAtNil sets the value for RequestedAt to be an explicit nil
func (o *HumanContactStatus) SetRequestedAtNil() {
	o.RequestedAt.Set(nil)
}

// UnsetRequestedAt ensures that no value is present for RequestedAt, not even an explicit nil
func (o *HumanContactStatus) UnsetRequestedAt() {
	o.RequestedAt.Unset()
}

// GetRespondedAt returns the RespondedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HumanContactStatus) GetRespondedAt() time.Time {
	if o == nil || IsNil(o.RespondedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RespondedAt.Get()
}

// GetRespondedAtOk returns a tuple with the RespondedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HumanContactStatus) GetRespondedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RespondedAt.Get(), o.RespondedAt.IsSet()
}

// HasRespondedAt returns a boolean if a field has been set.
func (o *HumanContactStatus) HasRespondedAt() bool {
	if o != nil && o.RespondedAt.IsSet() {
		return true
	}

	return false
}

// SetRespondedAt gets a reference to the given NullableTime and assigns it to the RespondedAt field.
func (o *HumanContactStatus) SetRespondedAt(v time.Time) {
	o.RespondedAt.Set(&v)
}

// SetRespondedAtNil sets the value for RespondedAt to be an explicit nil
func (o *HumanContactStatus) SetRespondedAtNil() {
	o.RespondedAt.Set(nil)
}

// UnsetRespondedAt ensures that no value is present for RespondedAt, not even an explicit nil
func (o *HumanContactStatus) UnsetRespondedAt() {
	o.RespondedAt.Unset()
}

// GetResponse returns the Response field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HumanContactStatus) GetResponse() string {
	if o == nil || IsNil(o.Response.Get()) {
		var ret string
		return ret
	}
	return *o.Response.Get()
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HumanContactStatus) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Response.Get(), o.Response.IsSet()
}

// HasResponse returns a boolean if a field has been set.
func (o *HumanContactStatus) HasResponse() bool {
	if o != nil && o.Response.IsSet() {
		return true
	}

	return false
}

// SetResponse gets a reference to the given NullableString and assigns it to the Response field.
func (o *HumanContactStatus) SetResponse(v string) {
	o.Response.Set(&v)
}

// SetResponseNil sets the value for Response to be an explicit nil
func (o *HumanContactStatus) SetResponseNil() {
	o.Response.Set(nil)
}

// UnsetResponse ensures that no value is present for Response, not even an explicit nil
func (o *HumanContactStatus) UnsetResponse() {
	o.Response.Unset()
}

// GetResponseOptionName returns the ResponseOptionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HumanContactStatus) GetResponseOptionName() string {
	if o == nil || IsNil(o.ResponseOptionName.Get()) {
		var ret string
		return ret
	}
	return *o.ResponseOptionName.Get()
}

// GetResponseOptionNameOk returns a tuple with the ResponseOptionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HumanContactStatus) GetResponseOptionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseOptionName.Get(), o.ResponseOptionName.IsSet()
}

// HasResponseOptionName returns a boolean if a field has been set.
func (o *HumanContactStatus) HasResponseOptionName() bool {
	if o != nil && o.ResponseOptionName.IsSet() {
		return true
	}

	return false
}

// SetResponseOptionName gets a reference to the given NullableString and assigns it to the ResponseOptionName field.
func (o *HumanContactStatus) SetResponseOptionName(v string) {
	o.ResponseOptionName.Set(&v)
}

// SetResponseOptionNameNil sets the value for ResponseOptionName to be an explicit nil
func (o *HumanContactStatus) SetResponseOptionNameNil() {
	o.ResponseOptionName.Set(nil)
}

// UnsetResponseOptionName ensures that no value is present for ResponseOptionName, not even an explicit nil
func (o *HumanContactStatus) UnsetResponseOptionName() {
	o.ResponseOptionName.Unset()
}

// GetSlackMessageTs returns the SlackMessageTs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HumanContactStatus) GetSlackMessageTs() string {
	if o == nil || IsNil(o.SlackMessageTs.Get()) {
		var ret string
		return ret
	}
	return *o.SlackMessageTs.Get()
}

// GetSlackMessageTsOk returns a tuple with the SlackMessageTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HumanContactStatus) GetSlackMessageTsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlackMessageTs.Get(), o.SlackMessageTs.IsSet()
}

// HasSlackMessageTs returns a boolean if a field has been set.
func (o *HumanContactStatus) HasSlackMessageTs() bool {
	if o != nil && o.SlackMessageTs.IsSet() {
		return true
	}

	return false
}

// SetSlackMessageTs gets a reference to the given NullableString and assigns it to the SlackMessageTs field.
func (o *HumanContactStatus) SetSlackMessageTs(v string) {
	o.SlackMessageTs.Set(&v)
}

// SetSlackMessageTsNil sets the value for SlackMessageTs to be an explicit nil
func (o *HumanContactStatus) SetSlackMessageTsNil() {
	o.SlackMessageTs.Set(nil)
}

// UnsetSlackMessageTs ensures that no value is present for SlackMessageTs, not even an explicit nil
func (o *HumanContactStatus) UnsetSlackMessageTs() {
	o.SlackMessageTs.Unset()
}

func (o HumanContactStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HumanContactStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RequestedAt.IsSet() {
		toSerialize["requested_at"] = o.RequestedAt.Get()
	}
	if o.RespondedAt.IsSet() {
		toSerialize["responded_at"] = o.RespondedAt.Get()
	}
	if o.Response.IsSet() {
		toSerialize["response"] = o.Response.Get()
	}
	if o.ResponseOptionName.IsSet() {
		toSerialize["response_option_name"] = o.ResponseOptionName.Get()
	}
	if o.SlackMessageTs.IsSet() {
		toSerialize["slack_message_ts"] = o.SlackMessageTs.Get()
	}
	return toSerialize, nil
}

type NullableHumanContactStatus struct {
	value *HumanContactStatus
	isSet bool
}

func (v NullableHumanContactStatus) Get() *HumanContactStatus {
	return v.value
}

func (v *NullableHumanContactStatus) Set(val *HumanContactStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableHumanContactStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableHumanContactStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHumanContactStatus(val *HumanContactStatus) *NullableHumanContactStatus {
	return &NullableHumanContactStatus{value: val, isSet: true}
}

func (v NullableHumanContactStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHumanContactStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
