{
 "title": "Example Traces",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Example Traces",
   "type": "traces",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.name=\"python-random-service\"}"
    }
   ]
  },
  {
   "title": "Curl Test Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "curl_test_metric", "legendFormat": "Curl Test Metric" }
   ]
  },
  {
   "title": "Curl Test Metric Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "curl_test_metric_ratio", "legendFormat": "Curl Test Metric Ratio" }
   ]
  }
 ]
}